name: CI Tests

on:
  push:
    branches:
    - main
  pull_request:

env:
  SETUP_XVFB: True  # avoid issues if mpl tries to open a GUI window

jobs:
  ci-tests:
    name: Tox env ${{ matrix.python }}-${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.8', '3.9', '3.10']
        toxenv: [test, test-alldeps, test-astropydev]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox extension-helpers
    - name: Install linetools requirements 
      run: |
        python -m pip install wheel scipy IPython astropy extension-helpers h5py qtpy pyaml
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
